# Use powerline
USE_POWERLINE="true"
# Has weird character width
# Example:
#    is not a diamond
HAS_WIDECHARS="false"
# Source manjaro-zsh-configuration
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  source /usr/share/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
#if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
#  source /usr/share/zsh/manjaro-zsh-prompt
#fi

get_git_branch() {
    local branch
    branch=$(git branch --show-current 2>/dev/null)
    [[ -n "$branch" ]] && echo "($branch)"
}

setopt PROMPT_SUBST
PROMPT='%F{#90EE90}%n%f@%m %F{#90EE90}%~%f $(get_git_branch)> '

export LS_COLORS="di=00;34"
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
