get_git_branch() {
    local branch
    branch=$(git branch --show-current 2>/dev/null)
    [[ -n "$branch" ]] && echo "($branch)"
}

setopt PROMPT_SUBST

PROMPT='%F{#90EE90}%n%f@%m %F{#90EE90}%~%f $(get_git_branch)> '

export LS_COLORS="di=00;34"

source ~/.config/zsh/zsh.conf
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
